movieproject2/credentials/urls.py
from django.urls import path
from . import views
app_name='credentials'
urlpatterns = [
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
]

movieproject2/movieproject2/urls.py
from django.contrib import admin
from django.urls import path,include

from movieproject2 import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/',include('mvapp.urls')),
    path('credentials/',include('credentials.urls')),
    path('search/',include('searchapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject2/mvapp/urls.py
from django.urls import path
from . import views
#app_name='mvapp'
urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('movies/category/<slug:category_slug>/', views.movie_list_by_category, name='movie_list_by_category'),
    path('movies/<slug:movie_slug>/', views.movie_detail, name='movie_detail'),
    path('add-movie/', views.add_movie, name='add_movie'),
    path('movies/<slug:movie_slug>/review/',views.post_review,name='post_review'),
    path('modify/<slug:movie_slug>/',views.modify,name='modify'),
    path('delete/<slug:movie_slug>/',views.delete,name='delete'),
]

movieproject2/searchapp/urls.py
from django.urls import path
from . import views

app_name='searchapp'
urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),
]

movieproject2/templates/add_movie.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h1>Add Movie</h1>
{% if not user.is_authenticated %}
<p>Please <a href="{% url 'credentials:login' %}">login</a> to add a movie</p>
{% else %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="name">Name:</label>
    <input type="text" id="name" name="name"><br><br>
    <label for="image">Poster:</label>
    <input type="file" id="image" name="image"><br><br>
    <label for="description">Description:</label>
    <textarea id="description" name="description"></textarea><br><br>
    <label for="release_date">Release Date:</label>
    <input type="date" id="release_date" name="release_date"><br><br>
    <label for="actors">Actors:</label>
    <input type="text" id="actors" name="actors"><br><br>
    <label for="category">Category:</label>
    <select id="category" name="category">
      {% for category in categories %}
        <option value="{{ category.slug }}">{{ category.name }}</option>
      {% endfor %}
    </select><br><br>
    <label for="trailer_link">Trailer Link:</label>
    <input type="url" id="trailer_link" name="trailer_link"><br><br>
    <button type="submit">Add Movie</button>
  </form>
{% endif %}
{% endblock %}

movieproject2/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/js/all.min.js" integrity="sha512-u3fPA7V8qQmhBPNT5quvaXVa1mnnLSXUep5PS1qo5NRzHwG19aHmNJnj1Q8hpA/nBWZtZD4r4AX6YOt5ynLN2g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <title>Movie Platform</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'nav.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

movieproject2/templates/delete.html
{% if not user.is_authenticated %}
<p>Please <a href="{% url 'credentials:login' %}">login</a> to delete the movie</p>
{% else %}
<form method="POST">
    {% csrf_token %}
    Do you want to delete this movie?
    <input type="submit">
</form>
{% endif %}

movieproject2/templates/edit.html
{% if not user.is_authenticated %}
<p>Please <a href="{% url 'credentials:login' %}">login</a> to update the movie</p>
{% else %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endif %}

movieproject2/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Edit Profile</h1>

<form method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" value="{{ user.username }}"><br><br>
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" value="{{ user.email }}"><br><br>
    <label for="first_name">First Name:</label>
    <input type="text" id="first_name" name="first_name" value="{{ user.first_name }}"><br><br>
    <label for="last_name">Last Name:</label>
    <input type="text" id="last_name" name="last_name" value="{{ user.last_name }}"><br><br>
    <button type="submit">Save</button>
</form>
{% endblock %}

movieproject2/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      display: flex;
      flex-direction: column;
      min-height: 100vh;
      margin: 0;
    }

    .content {
      flex: 1;
    }

    .footer {
      background-color: #f8f9fa;
      padding: 10px;
      text-align: center;
    }
  </style>
</head>
<body>

  <div class="content">
  </div>

  <footer class="footer">
    <p>movie platform</p>
  </footer>

</body>
</html>

movieproject2/templates/header.html
{% load static %}
<header>
  <center>
    <h1>Movie Platform</h1>
  </center>
</header>

movieproject2/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h5>login</h5>
<form action="{% url 'credentials:login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter user name"><br>
    <input type="password" name="password" placeholder="Enter first password"><br>
    <input type="submit">
</form>
{% endblock %}

movieproject2/templates/movie_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="row my_product_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'movie_list' %}">Home</a>| {{movie.name}}</p>
    </div>
</div>
<div class="container">
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{movie.image.url}}" alt="{{movie.name}}" height="200px;" width="200px;">
        </div>
    </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 ">
            <div>
            <h1 class="my_prod_title">{{movie.name}}</h1>
            <p>movie.release_date</p>
            <p class="text-justify my_prod_text">{{movie.description}}</p>
              <p>Actors: {{ movie.actors }}</p>
             <p>Trailer: <a href="{{ movie.trailer_link }}">Watch Trailer</a></p>
            <a class="btn btn-warning" href="{% url 'modify' movie.slug %}">Update</a>
            <a class="btn btn-danger" href="{% url 'delete' movie.slug %}">Delete</a>
        </div>
    </div>
    </div>
</div>
<br><br>
<br><br>
<div class="container" >
  <h2>Post Review</h2>
<form method="post">
  {% csrf_token %}
  <label for="rating">Rating:</label>
  <input type="number" id="rating" name="rating"><br><br>
  <label for="review">Review:</label>
  <textarea id="review" name="review"></textarea><br><br>
  <button type="submit">Post</button>
</form>
  <br><br>
    <div class="container">
<h2>Reviews:</h2>
<ul>
  {% for review in reviews %}
  <li>
    <p>Rating:{{review.rating}}</p>
    <p>Review:{{review.review}}</p>
  </li>
  {% endfor %}
</ul>
      </div>
  </div>
{% endblock %}


<!--  <h1>Movie Detail</h1>-->
<!--  <p>Name: {{ movie.name }}</p>-->
<!--  <p>Released: {{ movie.release_date }}</p>-->
<!--  <p>Category: {{ movie.category.name }}</p>-->
<!--  <p>Poster: {% if movie.image %}<img src="{{ movie.image.url }}" alt="Poster" style="width:200px;height:300px;">{% endif %}</p>-->
<!--  <p>Description: {{ movie.description }}</p>-->
<!--  <p>Actors: {{ movie.actors }}</p>-->
<!--  <p>Trailer: <a href="{{ movie.trailer_link }}">Watch Trailer</a></p>-->
<!--<a class="btn btn-warning" href="{% url 'modify' movie.slug %}">Update</a>-->
<!--<a class="btn btn-danger" href="{% url 'delete' movie.slug %}">Delete</a>-->
<!--<br><br>-->

movieproject2/templates/movie_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if category %}

    <div>
        <div class="row my_row_class" >
            <div class="mx_auto">
            <p><a href="{% url 'movie_list' %}">Movie Collections</a> </p>
        </div>
            </div>
    </div>
{% endif %}
    {% if category %}
<div>
        <h1 class="text-center my_title">{{category.name}}</h1>
</div>
{% else %}
<div>
    <h1 class="text-center my_title">Movie Collections</h1>
</div>
{% endif %}


<div class="container">
    <div class="row mx_auto">
        {% for movie in movies %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{% url 'movie_detail' movie.slug %}"><img class="card-img-top my_image" src="{{movie.image.url}}" alt="{{movie.name}}" height="340px;" width="340px;"> </a>
            <div class="card-body">
                <h4>{{movie.name}}</h4>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if movies.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in movies.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if movies.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>

{% if messages %}
<ul>
  {% for message in messages %}
  <script>
    alert('{{message}}');
  </script>
  {% endfor %}
</ul>
{% endif %}
{% endblock %}


<!--    {% for movie in movies %}-->
<!--      <li>-->
<!--        <p><a href="{% url 'movie_detail' movie.slug %}">{{ movie.name }}</a></p>-->
<!--        <p>Released: {{ movie.release_date }}</p>-->
<!--        <p>Category: {{ movie.category.name }}</p>-->
<!--        <p>Poster: {% if movie.image %}<img src="{{ movie.image.url }}" alt="Poster" style="width:100px;height:150px;">{% endif %}</p>-->
<!--      </li>-->
<!--    {% empty %}-->
<!--      <li>No movies found.</li>-->
<!--    {% endfor %}-->

movieproject2/templates/nav.html
`<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'movie_list' %}">Home</a>
        </li>
           <li class="nav-item dropdown {% if 'movie' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Movie
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'movie_list' %}">All Movies</a></li>
              {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{ cat.name }}</a></li>
              {% endfor %}
          </ul>
        </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_movie' %}">Add Movie</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'credentials:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'credentials:profile' %}">Profile</a>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'credentials:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'credentials:login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
      <form class="d-flex" action="{% url 'searchapp:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

movieproject2/templates/post_review.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Posted successfully</h2>
<p><a href="{% url 'movie_detail' movie_slug %}">Back</a></p>
{% endblock %}

movieproject2/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Profile</h1>

<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>First Name: {{ user.first_name }}</p>
<p>Last Name: {{ user.last_name }}</p>

<a href="{% url 'credentials:edit_profile' %}">Edit Profile</a>
{% endblock %}

movieproject2/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for :<b>"{{query}}"</b>
    </p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for movie in movies %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{movie.get_url}}"><img class="card-img-top my_image" src="{{movie.image.url}}" alt="{{movie.name}}" width="400px;" height="400px;"> </a>
            <div class="card-body">
                <p><a href="{% url 'movie_detail' movie.slug %}">{{ movie.name }}</a></p>
            </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text"> 0 results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}